# Generated by Django 4.0.3 on 2022-07-12 10:31

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='consulting_center',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='consulting_center',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='consulting_center',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='consulting_center',
            name='website',
            field=models.CharField(blank=True, max_length=500, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='news',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='news',
            name='date_posted',
            field=models.CharField(blank=True, default=api.models.special_date, max_length=100, verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='consulting_center',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='consulting_center',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='consulting_center',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
    ]
